### ISSUE TITLE
Error Building SML on multiple platforms 

### ISSUE THREAD

**Issue by nirmalsinghania2008** [solettaproject/soletta-machine-learning#64]
There is problem building SML on multiple distros.i tried it build in ubuntu,arch linux but it gives a hard time building sml.
The problem is the dependency fuzzylite which is not creating correct bindings in pkg-config and the default lib destination is also not which system recognizes.

having fuzzylite as dependency,people are having hard time setting up SML dev environment.
also there is no good support for fuzzylite on how to build it on different systems properly.
We should do something about it.
any solutions(temporary or permanent)?

**Comment by nirmalsinghania2008** [comment]
I found a fix for ubuntu platform(it worked in my case)
Just add this ppa repository
sudo add-apt-repository ppa:solettaproject/deps
then run
sudo apt-get update

then follow the usual installation steps

**Comment by bdilly** [comment]
@nirmalsinghania2008 I would suggest you to open a ticket about issues when building fuzzylite on its bug tracker (issues related to pkg-config / lib destination) and see what they say about it.

If there are issues with packaging you could open tickets about it in your distro bug tracker so they could fix it (ubuntu or arch).

It's the best way to approach this issue imo.

Thanks
